#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ethos_viewer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ethos")]
	public partial class ethosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertetho(etho instance);
    partial void Updateetho(etho instance);
    partial void Deleteetho(etho instance);
    #endregion
		
		public ethosDataContext() : 
				base(global::ethos_viewer.Properties.Settings.Default.ethosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ethosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ethosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ethosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ethosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<etho> ethos
		{
			get
			{
				return this.GetTable<etho>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ethos")]
	public partial class etho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _quote;
		
		private System.Data.Linq.Binary _pic;
		
		private string _addedBy;
		
		private System.DateTime _addedOn;
		
		private double _rank;
		
		private string _attrib;
		
		private string _url;
		
		private System.Nullable<bool> _nsfw;
		
		private System.Nullable<bool> _special;
		
		private string _hash;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnquoteChanging(string value);
    partial void OnquoteChanged();
    partial void OnpicChanging(System.Data.Linq.Binary value);
    partial void OnpicChanged();
    partial void OnaddedByChanging(string value);
    partial void OnaddedByChanged();
    partial void OnaddedOnChanging(System.DateTime value);
    partial void OnaddedOnChanged();
    partial void OnrankChanging(double value);
    partial void OnrankChanged();
    partial void OnattribChanging(string value);
    partial void OnattribChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnnsfwChanging(System.Nullable<bool> value);
    partial void OnnsfwChanged();
    partial void OnspecialChanging(System.Nullable<bool> value);
    partial void OnspecialChanged();
    partial void OnhashChanging(string value);
    partial void OnhashChanged();
    #endregion
		
		public etho()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quote", DbType="VarChar(4000)")]
		public string quote
		{
			get
			{
				return this._quote;
			}
			set
			{
				if ((this._quote != value))
				{
					this.OnquoteChanging(value);
					this.SendPropertyChanging();
					this._quote = value;
					this.SendPropertyChanged("quote");
					this.OnquoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pic", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary pic
		{
			get
			{
				return this._pic;
			}
			set
			{
				if ((this._pic != value))
				{
					this.OnpicChanging(value);
					this.SendPropertyChanging();
					this._pic = value;
					this.SendPropertyChanged("pic");
					this.OnpicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addedBy", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string addedBy
		{
			get
			{
				return this._addedBy;
			}
			set
			{
				if ((this._addedBy != value))
				{
					this.OnaddedByChanging(value);
					this.SendPropertyChanging();
					this._addedBy = value;
					this.SendPropertyChanged("addedBy");
					this.OnaddedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addedOn", DbType="DateTime NOT NULL")]
		public System.DateTime addedOn
		{
			get
			{
				return this._addedOn;
			}
			set
			{
				if ((this._addedOn != value))
				{
					this.OnaddedOnChanging(value);
					this.SendPropertyChanging();
					this._addedOn = value;
					this.SendPropertyChanged("addedOn");
					this.OnaddedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rank", DbType="Float NOT NULL")]
		public double rank
		{
			get
			{
				return this._rank;
			}
			set
			{
				if ((this._rank != value))
				{
					this.OnrankChanging(value);
					this.SendPropertyChanging();
					this._rank = value;
					this.SendPropertyChanged("rank");
					this.OnrankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attrib", DbType="VarChar(80)")]
		public string attrib
		{
			get
			{
				return this._attrib;
			}
			set
			{
				if ((this._attrib != value))
				{
					this.OnattribChanging(value);
					this.SendPropertyChanging();
					this._attrib = value;
					this.SendPropertyChanged("attrib");
					this.OnattribChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="VarChar(4096)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsfw", DbType="Bit")]
		public System.Nullable<bool> nsfw
		{
			get
			{
				return this._nsfw;
			}
			set
			{
				if ((this._nsfw != value))
				{
					this.OnnsfwChanging(value);
					this.SendPropertyChanging();
					this._nsfw = value;
					this.SendPropertyChanged("nsfw");
					this.OnnsfwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_special", DbType="Bit")]
		public System.Nullable<bool> special
		{
			get
			{
				return this._special;
			}
			set
			{
				if ((this._special != value))
				{
					this.OnspecialChanging(value);
					this.SendPropertyChanging();
					this._special = value;
					this.SendPropertyChanged("special");
					this.OnspecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hash", DbType="NVarChar(50)")]
		public string hash
		{
			get
			{
				return this._hash;
			}
			set
			{
				if ((this._hash != value))
				{
					this.OnhashChanging(value);
					this.SendPropertyChanging();
					this._hash = value;
					this.SendPropertyChanged("hash");
					this.OnhashChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
